[package]
name = "hypurh/foundry"
description = "This is essentially a module loader factory."
version = "0.1.2"
authors = ["hypurh"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["selene.toml", "sourcemap.json", "rokit.toml", "roblox.yml", "build.rbxm"]

[dependencies]
Promise = "evaera/promise@4.0.0"